### ISSUE TITLE
Extension stop working.

### ISSUE THREAD

**Issue by quyle92** [ctf0/close-to-the-left#2]
Hi there,
Thanks for creating great plugin for vscode community.

I've been using it for a year now without any issues but some reasons, the plugin's stopped working recently.

I am not sure why is that?

Thanks,
Q.

Vscode version: 1.77.1

**Comment by ctf0** [comment]
thanks for your kind words, atm its working correctly on my end
```
Version: 1.78.0-insider
Commit: ea0e3e0d1fabf0622fbcacdc4fe1c7b73b34dc0b
Date: 2023-04-07T05:40:56.611Z
Electron: 22.4.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

**Comment by ctf0** [comment]
also the ext is basically an alias for the internal vscode cmnd, check https://github.com/ctf0/close-tabs-to-the-left/blob/master/package.json

**Comment by swrobel** [comment]
Same issue here, on VSCode 1.77.3. Not sure why it spontaneously stopped working, but I see the following in the VSCode output tab (not sure if this same message was popping up back when this extension was working - never took note):
> [ctf0.close-tabs-to-the-left]: Command `workbench.action.closeEditorsToTheLeft` appears multiple times in the `commands` section.

Also worth noting that running the "Close Editors to the Left in Group" command from the command palette behaves as expected, as does the built-in "Close to the Right" command. It's just the context menu item that this extension adds that isn't working.

Update: just tested the insiders build, and the behavior is the same
```
Version: 1.78.0-insider
Commit: e410e7c66e7ce5c6bc31f73150d66857804a0ee9
Date: 2023-04-28T12:48:09.032Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes
```

**Comment by ctf0** [comment]
regarding the error u see, this is the default with vscode and its been there since the beginning, so no worries 

after some testing
- running `workbench.action.closeEditorsToTheLeft` from the command pallets works
- running the `close to the left` which use the same command, does nothing 😂

i think we need to open a ticket on vscode repo

**Comment by ctf0** [comment]
after some testing
- running `workbench.action.closeEditorsToTheLeft` from the command pallets works
- running the `close to the left` which use the same command, does nothing 😂

**Comment by bvoq** [comment]
that would be great!
I have the same issue.

**Comment by idontlikecreatingaccounts** [comment]
Installed today for the first time. Does not work. VSCode version 1.79.2.

**Comment by ctf0** [comment]
after more investigation i found a couple of more things
- atm when using the command pallet u will find a command call `View: Close Editors to the Left in Group` which i cant find under the editor keybindings
- the command `workbench.action.closeEditorsToTheLeft` close editors on the left of the active editor (same as `View: Close Editors to the Left in Group`), not the one u right clicked in the tabs bar, honestly am not sure if it was like this all along or it was changed

unfortunately the api doesn't give enough info about the tab position, like what comes before it or after it or even what group is it at.

anyway the extension is fixed now.

**Comment by quyle92** [comment]
@ctf0 thanks for your hard work.
