### ISSUE TITLE
Extension doesn't take into question where clicked

### ISSUE THREAD

**Issue by idontlikecreatingaccounts** [ctf0/close-to-the-left#3]
When clicking a tab and choosing "close to the right", VScode closes tabs to the right of the tab that was clicked.
With this extension, clicking "close to the left" closes tabs to the left of whichever tab is open at the moment, regardless of which tab was clicked.

I don't know if this is a purposeful design decision, but the inconsistency between left and right can be a bit jarring.

**Comment by ctf0** [comment]
check https://github.com/ctf0/close-tabs-to-the-left/issues/2
